<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Consultant extends BaseConsultant
{
    public function setUp()
    {
        $this->actAs('Searchable', array('fields' => array('UserName', 'Password')));
        parent::setUp();
    }
}